### PR TITLE
revert from merge feature/counter_five_align_with_capture, should fix…

### PR DESCRIPTION
**Pull request by arlaine4**
fixing soft locks and unwrap crashes that I brought back with my previous PR (I don't know how but it seems that is was the problem)

### CODE REVIEW

**Comment by demonoidv** [comment]
Why not requesting a review from @abassibe as well on this one as it's about Python?
BTW, I'll do my best trying to review but I'm really not an expert, sorry 😅

**Comment by demonoidv** [comment]
Can you explain to us what was the bug and how this PR fixes it, please? (It will help us not to reproduce the same mistakes)

I have to admit that it's still unclear to me how you managed to fix an unwrap's panic (which, I believe, is something that happens on the Rust side of the project), only by modifying Python files￼￼

**Comment by arlaine4** [comment]
Idk I thought I fixed it, but on my machine its not fixed (I'm sure i'm using the correct library and everything, I checked with @Ragarnoy ) but when we try to reproduce a soft lock or an unwrap crash, we can't manage to do so
We can't reproduce the bugs on @Ragarnoy computer, but we can on mine

**Comment by arlaine4** [comment]
And for the bugs, Its softlocks here and there, seems like its happening when you place a fifth stone to complete a five align, and with the unwrap crash, Idk seems kinda random, its happens sometimes, always when the AI thinks that there is nothing she can do to win
But the thing is, its not happening all the time, Its really confusing, and when I opened this PR I thought I fixed it but i was wrong

**Comment by Ragarnoy** [comment]
no idea what triggers it because I can't trigger it on my session for some reason.

**Comment by arlaine4** [comment]
the issues were from my computer, I had two bin folders, and the python interpreter was set to the wrong bin folder lol
kill me already I spent 2 days on this
The Python was getting the rust lib from :
`<module 'rust_ext' from '/Users/arlaine/Projects/Gomoku/lib/python3.7/site-packages/rust_ext.cpython-37m-darwin.so'>`
instead of :
`<module 'rust_ext' from '/Users/arlaine/Projects/Gomoku/venv/lib/python3.7/site-packages/rust_ext.cpython-37m-darwin.so'>`

I'm closing this PR since It's useless, the bugs don't exist I was all because of the Python interpreter

**Pull request closed without merging**
